### ISSUE TITLE
偶发性无法正常刷怪

### ISSUE THREAD

**Issue by hyb-oyqq** [GuizhanCraft/ElectricSpawners-CN#7]
## 描述
电动刷怪笼偶尔偶尔无法正常开机刷怪，但gui界面可以正常打开并控制开关

##重现问题的步骤
无

## 预期行为
正常开机并刷怪

## Server Log / Error Report
服务器在开机时确实有一个报错，但我不确定此报错和此bug是否具有关联性

```
 [19:20:56] [Craft Scheduler Thread - 27 - ElectricSpawners/WARN]: [ElectricSpawners] Plugin ElectricSpawners vBuild 4 zh-CN(ybw0014) (git 0d7b9bb) generated an exception while executing task 102
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
at com.google.gson.JsonParser.parseReader(JsonParser.java:66) ~[gson-2.8.9.jar:?]
at com.google.gson.JsonParser.parseString(JsonParser.java:47) ~[gson-2.8.9.jar:?]
at com.google.gson.JsonParser.parse(JsonParser.java:98) ~[gson-2.8.9.jar:?]
at io.github.thebusybiscuit.electricspawners.guizhanlib.utils.JsonUtil.parse(JsonUtil.java:20) ~[ElectricSpawners-Build 4 zh-CN(ybw0014) (git 0d7b9bb).jar:?]
at io.github.thebusybiscuit.electricspawners.guizhanlib.updater.UpdaterTask.getVersionFormat(UpdaterTask.java:68) ~[ElectricSpawners-Build 4 zh-CN(ybw0014) (git 0d7b9bb).jar:?]
at io.github.thebusybiscuit.electricspawners.guizhanlib.updater.UpdaterTask.run(UpdaterTask.java:47) ~[ElectricSpawners-Build 4 zh-CN(ybw0014) (git 0d7b9bb).jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-388]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-388]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.9.jar:?]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541) ~[gson-2.8.9.jar:?]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
at com.google.gson.JsonParser.parseReader(JsonParser.java:61) ~[gson-2.8.9.jar:?]
... 11 more

```

﻿

## 环境
Paper git-Paper-388 (MC: 1.18.2)
Slimefun 2024.04-release
Metrics-组件 #28
Java 17

安装的附属插件: (16)
  DyedBackpacks vBuild 1 zh-CN(baoad) (git 823de85)
  GuizhanLibPlugin vBuild 44 (git 1f5d835)
  ExtraTools vBuild 1 zh-CN(baoad) (git 5b1065a)
  SfChunkInfo vBuild 1 zh-CN(ybw0014) (git 5a90c94)
  Residence v5.1.5.0
  EcoPower vBuild 1 zh-CN(ybw0014) (git eca8ab1)
  ExtraGear vBuild 2 zh-CN(ybw0014) (git ff13031)
  SlimefunLuckyBlocks vBuild 1 zh-CN(baoad) (git d435fa3)
  ExoticGarden vBuild 4 zh-CN(ybw0014) (git b7cce7e)
  SlimeGlue v1.0.2-b262a4a
  ElectricSpawners vBuild 4 zh-CN(ybw0014) (git 0d7b9bb)
  SimpleUtils vBuild 1 zh-CN(baoad) (git 721f4c9)
  LocketteX v1.8.0
  PrivateStorage vBuild 1 zh-CN(ybw0014) (git 7205ea3)
  ColoredEnderChests vBuild 4 (git c99f079)
  SlimyRepair vBuild 1 (git 790c41c)

**Comment by ybw0014** [comment]
报错是自动更新的，刷怪需要周围指定生物数量少于 6
